### ISSUE TITLE
DataMatrixWriter generates wrong BitMatrix

### ISSUE THREAD

**Issue by HeikoOtt** [zxing/zxing#300]
When trying to encode the string "*DTCP01" (without quotes), the DataMatrixWriter delivers a wrong BitMatrix. The BitMatrix represents the string "*DTCP04 47" (without quotes).

The issue is easy to reproduce with the given string. Other examples work.

This is actually a very annoying issue, since the reason for the behavior is not clear. Seems to be somehow related to the leading asterix.

Remark:
Barcode4j has the same issue. IText's BarcodeDatamatrix renders the barcode as expected.
As far as I understood the zxing package history, the DataMatrix implementation is based on Barcode4j - so maybe this is an inherited issue.

**Comment by HeikoOtt** [comment]
Simplified test:

        DataMatrixWriter dmw = new DataMatrixWriter();
        BitMatrix b = dmw.encode("*DTCP01", BarcodeFormat.DATA_MATRIX, 64, 64);
        BufferedImage bi = MatrixToImageWriter.toBufferedImage(b);

**Comment by HeikoOtt** [comment]
accidentally closed - sorry

**Comment by srowen** [comment]
I tried this with the latest code in `master`, using `CommandLineEncoder` and `CommandLineRunner`, and got the expected `*DTCP01` out. I think a few issues have been fixed in DM over the past few months, so I would try this again with the latest code to see if that works.

**Comment by micjahn** [comment]
I can reproduce it with a min and max size of 10.
<CommandLineEncoder> --width=10 --height=10 ...
In that case the X12_UNLATCH isn't added in the X12Encoder.

**Comment by HeikoOtt** [comment]
Thanks for the prompt feedback to both of you! I used the latest code an can confirm both observations. The issue is gone when I use my example above. I still have the issue when using 0,0 or 10, 10 as micjahn described.

**Comment by srowen** [comment]
A-ha, yes I see that. The result is then `*DTCP04 47`. @micjahn have you narrowed it down enough to propose a fix? I usually don't know the formats well enough at this level to fix these things, but, here it might be clear enough once I step through.

**Comment by srowen** [comment]
Hm, in this case, the given dimension is so small that only 5 codewords can be encoded. After encoding 6 of the 7 characters, all 5 are used up. The code doesn't write the unlatch, but a comment in the code says it's not required, which I could believe (i.e. the decoder assumes an unlatch when there can't be another triplet in the stream because there's only 1-2 codewords left). However it has still got 1 character to encode and it actually *encodes* it in ASCII, but that 6th character is dropped. That itself seems like a little bug, but the right behavior is to fail the encoding, right? there isn't enough room in any encoding? That is to say I am not sure if it's an example of _this_ issue.

**Comment by micjahn** [comment]
I think the followiing patch is the  solution:
```
@@ -78,7 +78,7 @@ final class X12Encoder extends C40Encoder {
       context.signalEncoderChange(HighLevelEncoder.ASCII_ENCODATION);
     } else if (count == 1) {
       context.pos--;
-      if (available > 1) {
+      if (available != 1) {
         context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
       }
       //NOP - No unlatch necessary
```
Small explanation, if one character is left and there is exactly one codeword free than you
dont have to unlatch.
In all other case you have to unlatch because there is enough room left or adding a codeword will result in a bigger symbol info.

**Comment by micjahn** [comment]
Hm, the previous patch only fixes that one case. If an additional character should be encoded which isn't supported by the X12 encoder than the result is garbage.
I added a german umlaut `*DTCP01ä`.
If an unlatch is necessary should be decided by the remaining characters in the context.
```
@@ -78,11 +78,15 @@ final class X12Encoder extends C40Encoder {
       context.signalEncoderChange(HighLevelEncoder.ASCII_ENCODATION);
     } else if (count == 1) {
       context.pos--;
-      if (available > 1) {
+      if (available != 1 || context.getRemainingCharacters() > 1) {
         context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
       }
       //NOP - No unlatch necessary
       context.signalEncoderChange(HighLevelEncoder.ASCII_ENCODATION);
+    } else {
+      if (context.getRemainingCharacters() > 1) {
+        context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
+      }
     }
   }
 }
```

**Comment by srowen** [comment]
I walked through the logic, and it seems OK. All but the last character are encoded as follows:

(X12 latch) : 238
`*DT` : 9 10
`CP0` : 104 141

There is no space left at this point within the currently smallest pattern that can fit, which holds 5 codewords. So it skips the unlatch and continues, and ends up encoding the final character in ASCII:

`1` : 50

It then picks a 12x12 pattern to fit 8 codewords, and fills the remaining 2 spots with padding. So, I don't see that this is encodable in 10x10?

I suppose the odd thing is that with 8 codewords, there is room for a latch, then. I don't know if it is supposed to go back and fix that, but I don't think it's the issue here?

**Comment by micjahn** [comment]
In my opinion the logic isn't OK. The method handleEOD should not only rely on the length of the current buffer. It should be based upon the remaining characters in the context object to determine how many characters are left. As far as I understand the specification the unlatch codeword can only be missed if there is only one character left for encoding before the error correction codewords are added.
That's not the case here. There are two padding codewords before error correction.
It looks more terrible if you try to encode data which needs an encodation switch from X12 to another one. If I try `*DTCP01äaaaÜÖöüß?AbCaaa` it results in something like this after decoding `*DTCP041UEXLBSY>V*ISC9>D4B*YMJ0X5CRWGO320,`
If I modify the source like I mentioned above the result is ok.

**Comment by srowen** [comment]
Yes, all OK except that last part, although I think we're on to a different issue. In 12x12, it sounds like it can't omit the unlatch.

I think I understand the logic now. Here's what I have after tweaking the condition a little bit for IMHO a tiny bit of extra clarity:

```
  @Override
  void handleEOD(EncoderContext context, StringBuilder buffer) {
    context.updateSymbolInfo();
    int available = context.getSymbolInfo().getDataCapacity() - context.getCodewordCount();
    int count = buffer.length();
    if (count == 2) {
      // Definitely going to have to encode more, in another mode, so unlatch
      context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
      // Back up 2 places
      context.pos -= 2;
      // Switch back to ASCII
      context.signalEncoderChange(HighLevelEncoder.ASCII_ENCODATION);
    } else if (count == 1) {
      // Back up 1 place
      context.pos--;
      // If available == 0, write an unlatch since we'll definitely have to expand the
      // code capacity anyway. If available >= 2, there's room for unlatch and 1 more
      // character, so unlatch. If available == 1, it depends on how much is left to encode
      // If 1, *don't* unlatch since in this case the unlatch is omitted in order to use
      // the last codeword to encode the 1 remaining. If more is remaining, unlatch, since
      // it will be necessary to expand the code capacity anyway.
      if (available == 0 || available >= 2 || context.getRemainingCharacters() >= 2) {
        context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
      }
      context.signalEncoderChange(HighLevelEncoder.ASCII_ENCODATION);
    } else {
      if (context.getRemainingCharacters() >= 2) {
         context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
      }
    }
  }
```

So in the last clause though, I understand why you don't unlatch with no data left to encode (I don't think this occurs though). But if you have 1 left to encode, don't you hit the same problem? If you expand the code capacity, don't unlatch, then encode the final char, you still have padding. Does this not still need the same check on `available`?

**Comment by micjahn** [comment]
I never reached the last clause with getRemainingCharacters == 1. If one is left to encode it was caught by `if (count == 1)`. But you are right. If that one case occurs it should also do an unlatch.
Nevertheless, I look through the logic and I think it can be written in a shorter and in my opinion clearer way:
```
  void handleEOD(EncoderContext context, StringBuilder buffer, int newMode) {
    context.updateSymbolInfo();
    int available = context.getSymbolInfo().getDataCapacity() - context.getCodewordCount();
    context.pos -= buffer.length();
    if (context.getRemainingCharacters() > 1 || available < context.getRemainingCharacters())
      context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
    context.signalEncoderChange(newMode);
  }
```

The encode method needs a little modification which makes it also a bit cleaner (of course, in my opinion). The method `signalEncoderChange(newMode);` is now only called at one place.
```
  @Override
  public void encode(EncoderContext context) {
    //step C
    int newMode = HighLevelEncoder.ASCII_ENCODATION;
    StringBuilder buffer = new StringBuilder();
    while (context.hasMoreCharacters()) {
      char c = context.getCurrentChar();
      context.pos++;

      encodeChar(c, buffer);

      int count = buffer.length();
      if ((count % 3) == 0) {
        writeNextTriplet(context, buffer);

        newMode = HighLevelEncoder.lookAheadTest(context.getMessage(), context.pos, getEncodingMode());
        if (newMode != getEncodingMode()) {
          break;
        }
      }
    }
    handleEOD(context, buffer, newMode);
  }
```

**Comment by srowen** [comment]
Thinking about it the other way around, the only case where you do not unlatch is where there is 1 character left and 1 codeword available, right? I think that matches the logic in both versions of the method above. I like your simpler version; is `context.getRemainingCharacters() != 1 || available != 1` an even simpler condition to latch?

The `handleEOD` method is overridden from the parent and that's harder to change, so I am not sure if that's as easy as this change.

Anyway both conditions make my little test case pass, for the `*DTCP01` case. I have it expecting the unlatch, before finally encoding the 1 and padding with 1 codeword: `238 9 10 104 141 254 50 129`

**Comment by marmar44** [comment]
GITHUB

**Comment by micjahn** [comment]
It is not only an even simpler condition. It covers another condition, too. If you give a minimum size for encoding which has more codewords (f.e. 20x20) available then remaining characters than the unlatch is missing in my version.

In case of `handleEOD` and the call to `signalEncoderChange`: the call can also be made in the `encode` method after `handleEOD`.

**Comment by srowen** [comment]
OK I pushed the minimal fix and test case. Comment if I've still missed something.

**Comment by micjahn** [comment]
The fix doesn't work for `*DTCP0`. `getRemainingCharacters` and `available` are both 0 in that case, which is `!= 1`. An unnessary unlatch is added. That alone would not be a big issue but because of `if (count > 0)` the encoding isn't changed, X12 is still active. The method HighLevelEncoder.encodeHighLevel adds now an additional unlatch. That are the resulting codewords:
`238 9 10 104 141 254 254 129`
That's my working version of the fix:
```
...
         if (context.getRemainingCharacters() > 1 || available > 1 || context.getRemainingCharacters() != available)
            context.writeCodeword(HighLevelEncoder.X12_UNLATCH);
         if (context.getNewEncoding() < 0)
            context.signalEncoderChange(HighLevelEncoder.ASCII_ENCODATION);
...
```

**Comment by srowen** [comment]
Hm, I added a test case for this though, and it shows that the result is `238 9 10 104 141 254 50 129` in this case. How did you reproduce this

**Comment by micjahn** [comment]
```
  @Test
  public void testX12Unlatch2() {
    String visualized = encodeHighLevel("*DTCP0");
    assertEquals("238 9 10 104 141", visualized);
  }
```
result:
`org.junit.ComparisonFailure: expected:<238 9 10 104 141[]> but was:<238 9 10 104 141[ 254 254 129]>`

**Comment by srowen** [comment]
Got it. I can't think of a simpler working change, so will take yours!

**Comment by micjahn** [comment]
Look's good now.
